### ISSUE TITLE
Incompatible with Mail 7.3

### ISSUE THREAD

**Issue by kergoth** [nompute/GMailinator#10]

**Comment by serialmetrics** [comment]
Any work around to get this code functioning again?

**Comment by nompute** [comment]
Haven't had a chance to upgrade to 10.9.3.  I'll see about updating the UUIDs and uploading a new build this weekend.

**Comment by serialmetrics** [comment]
can you tell us which file contains the UUIDs and I can see about updating them, and re-compiling here?  Also, is your app comparable with rui carom’s vim keybinding script?  His does everything I want except for archiving email :(

**Comment by nompute** [comment]
The project has a script, find_uuid.sh, that you can run to grab the latest UUIDs for Mail 7.3.  Also, I don't think Rui Carmo's script will work with this - have you tried it with the latest Mail.app?  The interfaces changed quite a bit and I've made changes in GMailinator in order to get things working almost 100%.  Pretty sure there's a bug in Mail.app's internal API for selecting previous/next thread.  This module should be a strict superset of Rui's script.

**Comment by serialmetrics** [comment]
Rui, has an updated app that works with 7.3.  Just tried it -works. 

I have the new UUIDs    

```
    MailCompatibilityUUID = "F4C26776-22B3-4A0A-96E1-EA8E4482E0B5”;
```

MessageCompatibilityUUID = "DAFFB2B4-77BC-4C25-8CE1-2405E652D54B";

What file should I update?

**Comment by nompute** [comment]
Add both to Info.plist, recompile and you should be good to go!

**Comment by serialmetrics** [comment]
IT WORKS!

THANK GOD!

This is an indispensable tool for me!!!!

Amir

**Comment by nompute** [comment]
Awesome, glad it works, and it makes me glad that people enjoy this little tool.  I'll keep the bug open until I can formally update this repo and build a new binary.

**Comment by nompute** [comment]
Latest release incorporates the new UUID for 10.9.3, grab it [here](https://github.com/nompute/GMailinator/releases/tag/0.9.1).

**Comment by kergoth** [comment]
Great, thanks :)

**Comment by serialmetrics** [comment]
Hello there - 

The latest version of Yosemite 10.10.2 beta breaks the functionality of the “move to folder” shortcut. Have you noticed this?
